// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sisharpriborn.BO;

public partial class Credit
{
    public string CreditId { get; set; }

    public string CustomerId { get; set; }

    public double NominalKredit { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public double Bunga { get; set; }

    public double MonthlyPayment { get; set; }

    public string StatusCredit { get; set; }

    public virtual Agreement Agreement { get; set; }

    public virtual Customer Customer { get; set; }
}