// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sisharpriborn.BO;

public partial class Dealer
{
    public string DealerId { get; set; }

    public string DealerName { get; set; }

    public string DealerAddress { get; set; }

    public string City { get; set; }

    public string Province { get; set; }

    public int TaxRate { get; set; }

    public virtual ICollection<DealerCarList> DealerCarLists { get; set; } = new List<DealerCarList>();

    public virtual ICollection<SalesPerson> SalesPeople { get; set; } = new List<SalesPerson>();

    public virtual ICollection<TestDriveNego> TestDriveNegos { get; set; } = new List<TestDriveNego>();
}