// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sisharpriborn.BO;

public partial class DealerCarList
{
    public string DealerCarId { get; set; }

    public string CarId { get; set; }

    public string DealerId { get; set; }

    public int? Stock { get; set; }

    public double DealerCarPrice { get; set; }

    public virtual Car Car { get; set; }

    public virtual Dealer Dealer { get; set; }
    public virtual ICollection<Agreement> Agreements { get; set; } = new List<Agreement>();

    public virtual ICollection<LetterOfIntent> LetterOfIntents { get; set; } = new List<LetterOfIntent>();

    public virtual ICollection<TestDriveNego> TestDriveNegos { get; set; } = new List<TestDriveNego>();
}