// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sisharpriborn.BO;

public partial class PaymentHistory
{
    public string PaymentId { get; set; }

    public string AgreementId { get; set; }

    public double Nominal { get; set; }

    public double? PaymentLeft { get; set; }

    public DateOnly PaymentDate { get; set; }

    public virtual Agreement Agreement { get; set; }
}