// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sisharpriborn.BO;

public partial class SalesPerson
{
    public string SalesPersonId { get; set; }

    public string SalesName { get; set; }

    public string DealerId { get; set; }

    public DateOnly BirthDate { get; set; }

    public DateOnly HireDate { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public virtual ICollection<Agreement> Agreements { get; set; } = new List<Agreement>();

    public virtual ICollection<ConsultHistory> ConsultHistories { get; set; } = new List<ConsultHistory>();

    public virtual Dealer Dealer { get; set; }

    public virtual ICollection<TestDriveNego> TestDriveNegos { get; set; } = new List<TestDriveNego>();
}