// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sisharpriborn.BO;

public partial class TestDriveNego
{
    public string Tdnid { get; set; }

    public string ConsultId { get; set; }

    public string DealerCarId { get; set; }

    public string DealerId { get; set; }

    public string CustomerId { get; set; }

    public string SalesPersonId { get; set; }

    public string Note { get; set; }

    public DateOnly Tdndate { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Dealer Dealer { get; set; }

    public virtual DealerCarList DealerCar { get; set; }

    public virtual SalesPerson SalesPerson { get; set; }
}