// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sisharpriborn.BO;

public partial class WarrantyClaim
{
    public string ClaimId { get; set; }

    public string WarrantyId { get; set; }

    public string ServiceCenter { get; set; }

    public DateOnly ServiceDate { get; set; }

    public double ServiceCost { get; set; }

    public string Note { get; set; }

    public virtual Warranty Warranty { get; set; }
}