// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sisharpriborn.BO;

public partial class Warranty
{
    public string WarrantyId { get; set; }

    public string AgreementId { get; set; }

    public int WarrantyPeriodDays { get; set; }

    public virtual Agreement Agreement { get; set; }

    public virtual ICollection<WarrantyClaim> WarrantyClaims { get; set; } = new List<WarrantyClaim>();
}