// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleASPMVCEF.Models;

public partial class Car
{
    public string CarId { get; set; }

    public string VIN { get; set; }

    public string ModelType { get; set; }

    public string FuelType { get; set; }

    public double BasePrice { get; set; }

    public virtual ICollection<DealerCarList> DealerCarLists { get; set; } = new List<DealerCarList>();
}