// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleASPMVCEF.Models;

public partial class ConsultHistory
{
    public string ConsultId { get; set; }

    public string CustomerId { get; set; }

    public string SalesPersonId { get; set; }

    public double Budget { get; set; }

    public DateOnly ConsultDate { get; set; }

    public string Note { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual SalesPerson SalesPerson { get; set; }
}