// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleASPMVCEF.Models;

public partial class Customer
{
    public string CustomerId { get; set; }

    public string CustomerName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string IdCardNumber { get; set; }

    public virtual ICollection<Agreement> Agreements { get; set; } = new List<Agreement>();

    public virtual ICollection<ConsultHistory> ConsultHistories { get; set; } = new List<ConsultHistory>();

    public virtual ICollection<Credit> Credits { get; set; } = new List<Credit>();

    public virtual ICollection<TestDriveNego> TestDriveNegos { get; set; } = new List<TestDriveNego>();
}