// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleASPMVCEF.Models;

public partial class LetterOfIntent
{
    public string Loiid { get; set; }

    public double NegoPrice { get; set; }

    public string DealerCarId { get; set; }

    public double? Discount { get; set; }

    public double? BookingFee { get; set; }

    public string PaymentMethod { get; set; }

    public virtual Agreement Agreement { get; set; }

    public virtual DealerCarList DealerCar { get; set; }
}