// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleASPMVCEF.Models;

public partial class OtherBenefit
{
    public string AgreementId { get; set; }

    public string Benefit { get; set; }

    public virtual Agreement Agreement { get; set; }
}